name: Flatpak-builder CI

on:
  push:
    branches:
    - main
    - 'flatpak-builder-1.*.x'
  pull_request:
    branches:
    - main
    - 'flatpak-builder-1.*.x'

env:
  DEBIAN_FRONTEND: noninteractive
  TESTS_TIMEOUT: 10 # in minutes

permissions:
  contents: read

jobs:
  check-autotools:
    name: Build with gcc and test
    runs-on: ubuntu-22.04
    steps:
    - name: Check out flatpak
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y findutils
        sudo apt-get install -y $(xargs < .github/dependencies.apt.txt)
    - name: configure
      run: ./autogen.sh --enable-werror
      env:
        CFLAGS: -fsanitize=undefined -fsanitize-undefined-trap-on-error -fsanitize=address -O2 -Wp,-D_FORTIFY_SOURCE=2
    - name: Build flatpak
      run: make -j $(getconf _NPROCESSORS_ONLN)
    - name: Run tests
      run: make check
      env:
        ASAN_OPTIONS: detect_leaks=0 # Right now we're not fully clean, but this gets us use-after-free etc
    - name: Check distribution
      run: make distcheck
      env:
        ASAN_OPTIONS: detect_leaks=0

  clang:
    name: Build with clang
    runs-on: ubuntu-22.04
    steps:
    - name: Check out flatpak
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y findutils clang
        sudo apt-get install -y $(xargs < .github/dependencies.apt.txt)
    - name: configure
      # We disable introspection because it fails with clang: https://bugzilla.redhat.com/show_bug.cgi?id=1543295
      run: ./autogen.sh --enable-werror --disable-introspection
      env:
        CC: clang
    - name: Build flatpak
      run: make -j $(getconf _NPROCESSORS_ONLN)

  check-meson:
    name: Ubuntu meson build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-22.04', 'ubuntu-24.04']
        compiler: ['gcc', 'clang']

    env:
      CC: ${{ matrix.compiler }}
      BASE_CFLAGS: -Wp,-D_FORTIFY_SOURCE=2
      BUILDDIR: builddir
      CONFIG_OPTS: -Denable_werror=true -Dinstalled_tests=true

    steps:
    - name: Check out flatpak-builder
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y meson debugedit ${{ matrix.compiler }}
        sudo apt-get install -y $(xargs < .github/dependencies.apt.txt)

    - name: Configure flatpak-builder
      run: meson setup --wrap-mode nodownload ${CONFIG_OPTS} ${BUILDDIR} .

    - name: Build flatpak-builder with Meson
      run: meson compile -C ${BUILDDIR}

    - name: Upload docs
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        overwrite: true
        name: docs
        path: |
          builddir/doc/

    - name: Run tests with Meson
      run: timeout --signal=KILL -v ${TESTS_TIMEOUT}m meson test -C ${BUILDDIR} --verbose

    - name: Upload test logs
      uses: actions/upload-artifact@v4
      if: failure() || cancelled()
      with:
        name: test logs
        path: |
          builddir/meson-logs/testlog.txt
          installed-test-logs/

    - name: Configure flatpak-builder with Meson wraps
      run: meson setup --wrap-mode=forcefallback ${CONFIG_OPTS} ${BUILDDIR}_wrap .

    - name: Build flatpak-builder with Meson wraps
      run: meson compile -C ${BUILDDIR}_wrap
