name: Flatpak-builder CI

on:
  push:
    branches:
    - main
    - 'flatpak-builder-1.*.x'
  pull_request:
    branches:
    - main
    - 'flatpak-builder-1.*.x'

env:
  DEBIAN_FRONTEND: noninteractive
  TESTS_TIMEOUT: 10 # in minutes

permissions:
  contents: read

jobs:
  check-meson:
    name: Ubuntu meson build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-24.04']
        compiler: ['gcc', 'clang']

    env:
      CC: ${{ matrix.compiler }}
      BASE_CFLAGS: -Wp,-D_FORTIFY_SOURCE=2
      BUILDDIR: builddir
      CONFIG_OPTS: -Dinstalled_tests=true

    steps:
    - name: Check out flatpak-builder
      # 6.0.2
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y findutils
        sudo apt-get install -y \
          ${{ matrix.compiler }} \
          $(xargs < .github/dependencies.apt.txt)

    - name: Configure flatpak-builder
      run: meson setup --wrap-mode nodownload ${CONFIG_OPTS} ${BUILDDIR} .

    - name: Build flatpak-builder with Meson
      run: meson compile -C ${BUILDDIR}

    - name: Upload docs
      # 7.0.0
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
      with:
        if-no-files-found: error
        overwrite: true
        name: docs
        path: |
          builddir/doc/

    - name: Run tests with Meson
      run: timeout --signal=KILL -v ${TESTS_TIMEOUT}m meson test -C ${BUILDDIR} --verbose

    - name: Upload test logs
      # 7.0.0
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
      if: failure() || cancelled()
      with:
        name: test logs
        path: |
          builddir/meson-logs/testlog.txt
          installed-test-logs/

    - name: Configure flatpak-builder with Meson wraps
      run: meson setup --wrap-mode=forcefallback ${CONFIG_OPTS} ${BUILDDIR}_wrap .

    - name: Build flatpak-builder with Meson wraps
      run: meson compile -C ${BUILDDIR}_wrap
