name: Flatpak-builder CI

on:
  push:
    branches:
    - main
    - 'flatpak-builder-1.*.x'
  pull_request:
    branches:
    - main
    - 'flatpak-builder-1.*.x'

env:
  #DEBIAN_FRONTEND: noninteractive
  TESTS_TIMEOUT: 10 # in minutes
  MESON_TEST_TIMEOUT_MULTIPLIER: 2

permissions:
  contents: read

jobs:
  check-meson:
    name: Ubuntu meson build
    runs-on: ${{ matrix.os }}
    container:
      image: fedora:44
      options: --privileged
    strategy:
      matrix:
        os: ['ubuntu-24.04']
        compiler: ['gcc', 'clang']

    env:
      CC: ${{ matrix.compiler }}
      BUILDDIR: builddir
      CONFIG_OPTS: -Dinstalled_tests=true

    steps:
    - name: Install dependencies
      run: |
        dnf upgrade --refresh -y
        dnf install -y git findutils

    - name: Set git safe directory
      run: |
        git config --global safe.directory "*"

    - name: Check out flatpak-builder
      # 6.0.2
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        persist-credentials: false

    - name: Install build dependencies
      run: |
        dnf install -y \
          ${{ matrix.compiler }} \
          $(xargs < .github/dependencies.dnf.txt)

    - name: Configure flatpak-builder
      run: |
        meson setup --wrap-mode nodownload ${CONFIG_OPTS} \
          -Dwerror=true \
          -Db_sanitize=address,undefined \
          ${BUILDDIR} .

    - name: Build flatpak-builder with Meson
      run: meson compile -C ${BUILDDIR}

    - name: Upload docs
      # 7.0.0
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
      with:
        if-no-files-found: error
        overwrite: true
        name: docs
        path: |
          builddir/doc/

    - name: Run tests with Meson
      env:
        ASAN_OPTIONS: "detect_leaks=1:fast_unwind_on_malloc=0:malloc_context_size=20:symbolize=1"
        UBSAN_OPTIONS: "print_stacktrace=1"
      run: |
        timeout --signal=KILL -v ${TESTS_TIMEOUT}m meson test -C ${BUILDDIR} --verbose --timeout-multiplier ${MESON_TEST_TIMEOUT_MULTIPLIER}

    - name: Create dist tarball
      run: |
        meson setup --wrap-mode nodownload --reconfigure ${CONFIG_OPTS} ${BUILDDIR}_dist .
        meson dist --include-subprojects -C ${BUILDDIR}_dist

    - name: Upload test logs
      # 7.0.0
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
      if: failure() || cancelled()
      with:
        name: test logs
        path: |
          builddir/meson-logs/testlog.txt
          installed-test-logs/
          builddir_dist/meson-private/dist-build/meson-logs/testlog.txt
